### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by RJP43** [ech45/immigration_station#2]
Pitt-Greensburg and others respond to this issue with your comments on the Immigration Project.

**Comment by RJP43** [comment]
One question that comes to mind for me and this project is of subjectivity. In your markup, there are points where you have marked the trope as "anti" and with that, I wonder if this is just black and white (as in anti and pro) or is there a moderate attribute?

**Comment by bsf15** [comment]
I thought the concept of this project was really interesting, especially when analyzing the language used in the debates. I know during the presentation, it was mentioned that there are plans to set up javascript to highlight the certain tropes/words and I think that will be very helpful when looking at the debates and specifically pulling out the content the project is focused on. I don't recall what was all planned to be incorporated with the javascript, but perhaps assigning a certain color or highlight to certain candidates when they are speaking could be an interesting addition to see which candidates used more of a certain trope more clearly while browsing through the debates.
As @RJP43 mentioned above about the possibility of a moderate attribute and if there is one, I think that could be a nice way to show if there is a middle ground being taken by any candidates in regards to immigration and really expand more into the analysis of the language. 
 I'm interested to see what else may be done with the candidates page with the photos and what type of information or etc will be available to view there. Overall though, the design / layout of the site so far fits the project and it is clear and easy to read through and it looks like there is a lot of information available to really investigate and analyze.

**Comment by Samantha-Mcguigan** [comment]
The main page of your site is absolutely beautiful! I love the idea of looking at how different candidates speak about immigration and tagging the words that surround immigration language. I noticed that you did it based on the republican and democratic debates which I think is a good way to narrow down the texts to code and gives you a good representation of how candidates  discuss immigration. I know we have a small time frame but it would be interesting to look at candidates outside of the two major parties to see how they differ. 
I was looking under your analysis page and I was a little confused on what the "Mutual Information Score" means? Also, I'm sure you are also still working on your project but it might be cool to add some SVG elements to your analysis. Perhaps a bar graph that that shows how many times each word is mentioned but for time's sake, limit it two the two major candidates: Clinton and Trump. It might also be cool to do a Network Analysis for these two connecting the speaker to the language used and the edge being which particular debate connects the two or something similar if that makes sense. 
Overall, the website itself looks amazing, just a few things to touch up like the alignment of the links in your header on some of the pages (the analysis link sitting slightly lower than the others) which I'm sure you are still working on anyway. The concept is super interesting as well, I think you took a good approach, I would just add some SVG elements.

**Comment by dotfig** [comment]
This is a brilliant topic, considering what has happened in the past year or so with the election and what not. I have looked through a few of your marked up text and something cool popped in my head. Have you guys noticed a difference in questions asked by the moderators? Do some moderators ask democrats differently phrased questions and vice versa? Can you find a bias from the moderators point of view. I think this final project is going to be very interesting to look through and see what you guys have created.  Excellent job!
